jobs:
  CloneRepo:
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/gradient-ai/gfpgan.git
  GetModel:
    resources:
      instance-type: C5
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      trained-model:
        type: dataset
        with:
          ref: dstk425ln2zhv8g
    uses: script@v1
    with:
      script: |-
        pip install flask
        cd inputs/repo
        mkdir flaskapp
        cd flaskapp
        mkdir upload 
        wget https://github.com/TencentARC/GFPGAN/releases/download/v0.2.0/GFPGANCleanv1-NoCE-C2.pth 
        flask myapp.py 
        cd ..
        cp -R flaskapp /outputs/trained-model

      image: "nvcr.io/nvidia/pytorch:21.10-py3"

  UploadModel:
    resources:
      instance-type: C5
    inputs:
      model: GetModel.outputs.trained-model
    outputs:
      model-id:
        type: string
    needs:
      - GetModel
    uses: create-model@v1
    with:
      name: trained-model
      type: Custom
